E-commerce/digikala/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('edit-profile/' , views.edit_profile , name='edit_profile'),
    path('get-cities/' , views.get_cities , name='get_cities'),
    path('login-view/' , views.login_view , name='login_view'),
    path('email-login/' , views.email_login , name='email_login'),
    path('logout-view/' , views.logout_view , name='logout_view'),
    path('register/' , views.register , name='register'),
    path('active-email/<str:encoded_user_id>/<str:token>/' , views.active_email , name='active_email'),
    path('mobile-login/' , views.mobile_login , name='mobile_login'),
    path('verify_otp/' , views.verify_otp , name='verify_otp'),
    path('resend_otp/' , views.resend_otp , name='resend_otp'),
]

E-commerce/digikala/digikala/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

E-commerce/digikala/shop/urls.py
from django.urls import path
from .views import verify,index ,store , checkout , detail ,add_to_cart ,cart_detail ,remove_from_cart,to_bank


app_name = 'shop'


urlpatterns = [
    path('index/' ,index,name='index' ),
    path('store/' ,store ,name='store'),
    path('<int:id>/<str:title>/' ,detail ,name='detail'),
    path('checkout/' ,checkout,name='checkout' ),
    path('to-bank/<int:order_id>/' ,to_bank,name='to_bank' ),
    path('verify/' ,verify,name='verify' ),
    path('add-to-cart' , add_to_cart , name='add_to_cart'),
    path('cart' , cart_detail , name='cart_detail'),
    path('cart/remove/<int:product_id>/' , remove_from_cart , name='remove_from_cart'),
    
]

E-commerce/digikala/shop/models.py
from django.db import models
from django.conf import settings
from accounts.models import City
# Create your models here.

# class User(models.Model):
#     mobile = models.CharField(max_length=11)
class BaseModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted = False)


class BaseModel(models.Model):
    deleted = models.BooleanField(default=False,editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BaseModelManager()

    class Meta:
        abstract = True

    def delete(self , using=None , keep_parents= False):
        self.deleted = True
        self.save()


class Category(BaseModel):
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title


class Product(BaseModel):
    title = models.CharField(max_length=100)
    content = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='image/product')
    quantity = models.PositiveIntegerField()
    status = models.BooleanField(default=True)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL ,null=True , blank=True)
    
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("shop:detail", kwargs={'id':self.id, 'title':self.title})


class Cart(BaseModel):
    quantity = models.PositiveIntegerField()
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)


class Order(BaseModel):
    total_price = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    status = models.BooleanField(null=True)
    note = models.CharField(max_length=200,blank=True)
    different_address = models.CharField(default=False,blank=True)
    first_name = models.CharField(max_length=50 , blank=True)
    last_name = models.CharField(max_length=50 , blank=True)
    mobile = models.CharField(max_length=11)
    address = models.CharField(max_length=200)
    city = models.ForeignKey(City , on_delete=models.SET_NULL ,null=True)
    postal_code = models.CharField(max_length=10) 
    zarinpal_authority = models.CharField(max_length=50 , null=True)
    zarinpal_ref_id = models.IntegerField(null=True )

class OrderProduct(BaseModel):
    product = models.ForeignKey(Product , on_delete=models.SET_DEFAULT , default=None , null=True)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.IntegerField()


class PaymentLog(BaseModel):
    amount = models.IntegerField()
    user_id = models.PositiveIntegerField()
    order_id = models.PositiveIntegerField()
    status = models.CharField(max_length=100)
    error_code = models.CharField(max_length=200)

E-commerce/digikala/shop/forms.py
from django import forms

class OrderForm(forms.Form):
    first_name = forms.CharField(max_length=50 )
    last_name = forms.CharField(max_length=50 )
    mobile = forms.CharField(max_length=11)
    address = forms.CharField(max_length=200)
    postal_code = forms.CharField(max_length=10) 
    city = forms.IntegerField() 

E-commerce/digikala/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .models import Product, Order
from django.http import Http404
from django.views.decorators.http import require_POST
from django.urls import reverse
from .cart import Cart
from django.contrib.auth.decorators import login_required
from .models import OrderProduct
from accounts.models import Profile, Province, City
from .forms import OrderForm
from django.conf import settings
from django.shortcuts import redirect
import json
import requests
# import requests

# Create your views here.


def index(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'index.html', context)


def store(request):
    category = request.GET.get('category')

    if category:
        products = Product.objects.filter(category__title=category)

    else:
        products = Product.objects.all()

    context = {
        'products': products
    }
    return render(request, 'store.html', context)


@login_required
def checkout(request):
    try:
        Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        return redirect(reverse('accounts:edit_profile') + '?next=' + reverse('shop:checkout'))

    cart = Cart(request)

    if request.method == 'POST':
        different_address = request.POST.get('different_address')
        order = None

        if different_address:
            order_form = OrderForm(request.POST)
            print("🧾 فرم ارسال شد، خطاهای احتمالی:", order_form.errors)
            if not order_form.is_valid():
                context = {'provinces': Province.objects.all(), 'form_errors': order_form.errors}
                return render(request, 'checkout.html', context)

            order = Order.objects.create(
                user=request.user,
                total_price=cart.get_total_price,
                note=request.POST.get('note', ''),
                different_address=True,
                first_name=order_form.cleaned_data['first_name'],
                last_name=order_form.cleaned_data['last_name'],
                mobile=order_form.cleaned_data['mobile'],
                postal_code=order_form.cleaned_data['postal_code'],
                address=order_form.cleaned_data['address'],
                city_id=order_form.cleaned_data['city'],
            )
        else:
            order = Order.objects.create(
                user=request.user,
                total_price=cart.get_total_price,
                different_address=False,
                note=request.POST.get('note', ''),
                first_name=request.user.first_name,
                last_name=request.user.last_name,
                mobile=request.user.mobile,
                postal_code=request.user.profile.postal_code,
                address=request.user.profile.address,
                city=request.user.profile.city,
            )

        # ذخیره محصولات سفارش
        for item in cart:
            OrderProduct.objects.create(
                order=order,
                product_id=item['product_id'],
                quantity=item['quantity'],
                price=item['price']
            )

        # cart.clear()
        return redirect(reverse('shop:to_bank', args=[order.id]))

    # حالت GET
    context = {
        'provinces': Province.objects.all(),
    }
    return render(request, 'checkout.html', context)


@login_required
def to_bank(request, order_id):
    cart = Cart(request)
    order = get_object_or_404(
        Order, id=order_id, user=request.user, status__isnull=True)

    data = {
        "merchant_id": settings.ZARINPAL_MERCHANT_ID,
        "amount": order.total_price,
        "description": f"Order #{order_id}",
        "callback_url": settings.ZARINPAL_CALLBACK_URL,
        "metadata": {"order_id": str(order.id), "email": request.user.email}
    }
    print("زرین‌پال request to_bank:", data)

    headers = {"Content-Type": "application/json"}

    try:
        response = requests.post(
            "https://sandbox.zarinpal.com/pg/v4/payment/request.json",
            data=json.dumps(data),
            headers=headers,
            timeout=10
        )
    except requests.exceptions.Timeout:
        return render(request, "to_bank.html", {"error": "Timeout error"})
    except requests.exceptions.ConnectionError:
        return render(request, "to_bank.html", {"error": "Connection error"})

    res_json = response.json()
    data = res_json.get("data", {})
    print("زرین‌پال verify response:", res_json)
    if response.status_code != 200:
        return render(request, "to_bank.html", {"error": f"HTTP {response.status_code}"})
    if data.get("code") != 100:
        
        return render(request, "to_bank.html", {"error": data.get("message", "Error")})

    authority = data["authority"]
    order.zarinpal_authority = authority
    order.status = False
    order.save()
    cart.clear()
    # ریدایرکت به درگاه پرداخت
    return redirect(f"https://sandbox.zarinpal.com/pg/StartPay/{authority}")


def verify(request):
    authority = request.GET.get('Authority')
    status = request.GET.get('Status')

    if not authority:
        return render(request, "verify.html", {"success": False, "error": "کد تراکنش موجود نیست."})

    order = Order.objects.filter(zarinpal_authority=authority).first()
    if not order:
        return render(request, "verify.html", {"success": False, "error": "سفارشی با این تراکنش پیدا نشد."})

    if status != 'OK':
        return render(request, "verify.html", {"success": False, "error": "پرداخت لغو شد یا انجام نشد."})

    data = {
        "merchant_id": settings.ZARINPAL_MERCHANT_ID,
        "amount": order.total_price,
        "authority": authority
    }
    print("زرین‌پال request to_bank:", data)

    headers = {"Content-Type": "application/json"}
    response = requests.post(
        settings.ZARINPAL_VERIFY_URL,
        data=json.dumps(data),
        headers=headers,
        timeout=10
    )

    print("زرین‌پال verify response:", response.text)  # 🔹 مهم برای debug

    res_json = response.json()
    data = res_json.get("data", {})

    if data.get("code") == 100:
        order.zarinpal_ref_id = data["ref_id"]
        order.status = True
        order.save()
        return render(request, "verify.html", {"success": True, "ref_id": data["ref_id"], "order": order})
    else:
        return render(request, "verify.html", {"success": False, "error": data})


def detail(request, id=int, title=str):

    product = get_object_or_404(Product, id=id)
    context = {
        'product': product
    }

    return render(request, 'detail.html', context)

@require_POST
def add_to_cart(request):
    product_id = request.POST.get('product_id')
    quantity = request.POST.get('quantity')
    product = get_object_or_404(Product, id=product_id)

    cart = Cart(request)

    cart.add(product_id, product.price, quantity)

    return redirect(reverse('shop:cart_detail'))


def remove_from_cart(request, product_id):

    cart = Cart(request)
    cart.remove(str(product_id))
    return redirect(reverse('shop:cart_detail'))
    # cart = request.session.get('cart')
    # pid = str(product_id)

    # if pid in cart:
    #         del cart[pid]
    #         request.session.modified = True


def cart_detail(request):

    return render(request, 'cart_detail.html')

E-commerce/digikala/shop/templates/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Electro - HTML Ecommerce Template</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		{% block styles %}
		{% endblock styles %}
    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
					</ul>
					<ul class="header-links pull-right">
						<li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
						<li><a href="{% url 'accounts:login_view'%}"><i class="fa fa-user-o"></i>
							 {% if user.is_authenticated %}
							 {{ user.username }}
							 {%else%}
								Sign-in/Sing-up
							 {% endif %}

							 
							</a>
						</li>
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="{% url 'shop:index' %}" class="logo">
									<img src="{% static './img/logo.png' %}" alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form>
									<select class="input-select">
										<option value="0">All Categories</option>
										<option value="1">Category 01</option>
										<option value="1">Category 02</option>
									</select>
									<input class="input" placeholder="Search here">
									<button class="search-btn">Search</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<div>
									<a href="#">
										<i class="fa fa-heart-o"></i>
										<span>Your Wishlist</span>
										<div class="qty">2</div>
									</a>
								</div>
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										<span>Your Cart</span>
										<div class="qty">{{cart_length}}</div>
									</a>
									<div class="cart-dropdown">
										<div class="cart-list">
											{% for item in cart %}
											<div class="product-widget">
												<div class="product-img">
													<img src="{{ item.product.image.url }}" alt="">
												</div>
												<div class="product-body">
													<h3 class="product-name"><a href="{{item.product.get_absolute_url}}">{{item.product.title}}</a></h3>
													<h4 class="product-price"><span class="qty">{{item.quantity}}x</span>{{item.price}}$</h4>
												</div>
												<a class="delete" href="{% url 'shop:remove_from_cart' item.product.id %}"><i class="fa fa-close"></i></a>
											</div>
											{% endfor %}

											
										</div>
										<div class="cart-summary">
											<small>{{cart_length}} Item(s) selected</small>
											<h5>SUBTOTAL: ${{FinalPrice}}</h5>
										</div>
										<div class="cart-btns">
										<a href="{% url 'shop:cart_detail'%}">View Cart</a>
											<a href="{% url 'shop:checkout'%}">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
										</div>
									</div>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="active"><a href="{% url 'shop:index' %}">Home</a></li>
						<li><a href="#">Hot Deals</a></li>
						<li><a href="#">Categories</a></li>
						<li><a href="#">Laptops</a></li>
						<li><a href="#">Smartphones</a></li>
						<li><a href="#">Cameras</a></li>
						<li><a href="#">Accessories</a></li>
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->
        {%block content%}
        {%endblock content%}
















		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->

		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
		{% block scripts %}
		{% endblock scripts %}
	</body>
</html>

E-commerce/digikala/shop/templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    cart
{% endblock title %}
{% block styles %}
<style>
    th , td {
        padding: 10px;
        text-align: center;
    }
    th{
        padding: 15px;
        margin-left: 5px;
    }
   
</style>

{% endblock styles %}
{% block content %}
<div class="container">
    <h1>cart detail</h1>
    {% if cart.cart_length == 0 %}
    <p style="font-size: xx-large;">Your Cart Is Empty !</p>
    <a href="{% url 'shop:store' %}" class="primary-btn order-submit">Countinue Shopping</a>
    {%else%}
        <table>
            <tr>
                <th>Product image</th>
                <th>Product title</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
            
        
                
                
            </tr>
            {% for item in cart %}
                <tr>
                    <td><img src="{{item.product.image.url}}" alt="" width="150"></td>
                    <td><a href="{{ item.product.get_absolute_url }}">{{item.product.title}}</a></td>
                    <td>{{item.price}}$</td>

                    <td>
                        <div class="add-to-cart">
                            <form method="POST" action="{% url 'shop:add_to_cart'%}">
                                <div class="qty-label">
                                    <div class="input-number">
                                        <input type="number" name="quantity" value="{{item.quantity}}">
                                        <input type="hidden" name="product_id" value="{{item.product.id}}">
                                        <button  class="qty-up">+</button>
                                        <button class="qty-down">-</button>
                                    </div>
                                </div>
                                <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> Update</button>
                                {%csrf_token%}
                            </form>
                        </div>
                    </td>
                    <td>{{item.TotalPrice}}$</td>
                    <td><a href="{% url 'shop:remove_from_cart' product_id=item.product.id %}">remove</a></td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"></td>
                    <td style="font-size: large;">TotalPrice :</td>
                    <td style="font-size: large;">{{cart.get_total_price}}$</td>
                </tr>
        </table>
        <a href="{% url 'shop:checkout'%}" class="primary-btn order-submit">Checkout</a>
        <a href="{% url 'shop:store' %}" class="primary-btn order-submit">Countinue Shopping</a>
        {% endif %}
        </div>
{% endblock content %}

E-commerce/digikala/shop/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    login
{% endblock title %}
{% block content %}
<div class="container">

    <h1>Login</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login">
        <a href="{% url 'accounts:register'%}">Register</a>
    </form>
     {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
           <p>{{message}}</p> 
        </div>
    {% endfor %}
    {% endif %}
    <hr />
    <a href="{% url 'accounts:mobile_login'%}">Mobile Login</a>
    <a href="{% url 'accounts:email_login'%}">Email Login</a>
    <!-- {% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger">
            {{message}}
        </div>
    {% endfor %}
    {% endif %} -->

   
</div>
{% endblock content %}

E-commerce/digikala/shop/templates/to_bank.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    To Bank
{% endblock title %}

{% block content %}
<div class="container">
    {{error}}   
</div>
{% endblock content %}

E-commerce/digikala/shop/templates/verify_otp.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Mobile Login
{% endblock title %}
{% block content %}
<div class="container">
    <h1>Verify OTP</h1>
    <form method="post" action="">
        <label for="mobile">OTP:</label>
        <input type="text" name="otp" id="otp">
        {% csrf_token %}
        <input type="submit" value="Login">
    </form>
    <p></p>
    <p id="timer-box">send otp again: <span id="timer">60 </span> seconds</p>
    <p id="resend-link"><a href="{% url 'accounts:resend_otp'%}">Resend otp</a></p>
    
    
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
           <p>{{message}}</p> 
        </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(function(){
        let timerBox = $('#timer-box')
        let timerSpan = $('#timer')
        let resendLink = $('#resend-link')
        let timeLeft = 60
        resendLink.hide()

        let interval = setInterval(function(){
            if (timeLeft <= 0){
                clearInterval(interval)
                resendLink.show();
                timerBox.hide()
            }else{
                timerSpan.text(timeLeft);
                timeLeft -= 1
            }
        },1000)

        
    })
</script>

{% endblock scripts %}